name: BuildAndTestFunctions
on:
  push:

  pull_request:
    branches:
    - master

jobs:

  build-test-linux:
    name: Build and test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        dotnet: ['2.1.230', '3.1.300']
    steps:

    - name: Check out code onto host
      uses: actions/checkout@v1

    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }} # SDK Version to use.

    - name: Run unit tests
      run: |
        dotnet test jose-jwt.sln

